version: 0.1
phases:
  install:
    commands:      
      # - aws cloudformation package --template-file samTemplate.yaml --s3-bucket vikram-cd-pipeline-lambda --output-template-file outputSamTemplate.yaml
      - aws cloudformation update-stack --stack-name lambdaCDPOCStatck --template-body file://samTemplate.yaml --stack-policy-body file://stackPolicy.json --capabilities CAPABILITY_AUTO_EXPAND
      # - aws cloudformation set-stack-policy --stack-name lambdaCDPOCStatck --stack-policy-body file://stackPolicy.json
      # - aws cloudformation update-stack --stack-name lambdaCDPOCStatck --stack-policy-body file://stackPolicy.json --capabilities CAPABILITY_AUTO_EXPAND
      
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
    - stackPolicy.json