AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda CD POC 
Resources:
  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda1.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambdas/lambda1
      Description: 'Lambda function for CD POC'
      MemorySize: 128
      Timeout: 30
      # Layers: 
      #   - Ref: CborLayer
      Role: 'arn:aws:iam::858701282395:role/lamdbaS3AccessRole'
      # Events:
      #   getAZsAPI:
      #     Type: Api
      #     Properties:
      #       Path: /getazs
      #       Method: get
      Environment:
        Variables:
          REGION: us-east-2

  Lambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda2.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambdas/lambda2
      Description: 'Lambda function for CD POC'
      MemorySize: 128
      Timeout: 30
      # Layers: 
      #   - Ref: CborLayer
      Role: 'arn:aws:iam::858701282395:role/lamdbaS3AccessRole'
      # Events:
      #   getAZsAPI:
      #     Type: Api
      #     Properties:
      #       Path: /getazs
      #       Method: get
      Environment:
        Variables:
          REGION: us-east-2

  # CborLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     ContentUri: ./layers/cbor-layer.zip
  #     CompatibleRuntimes:
  #       - python3.8
  #   Metadata:
  #     BuildMethod: python3.8